/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package file.security.system.using.otp;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.File;



/**
 *
 * @author Ajeet
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7_minimize = new javax.swing.JLabel();
        jLabel8_close = new javax.swing.JLabel();
        jButton_Register = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Fullname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jTextField_Phone = new javax.swing.JTextField();
        jPasswordField_1 = new javax.swing.JPasswordField();
        jPasswordField_2 = new javax.swing.JPasswordField();
        jLabel_Login_Account = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("    Register");

        jLabel7_minimize.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7_minimize.setText("  -");
        jLabel7_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7_minimizeMouseExited(evt);
            }
        });

        jLabel8_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8_close.setText("   X");
        jLabel8_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256)
                .addComponent(jLabel7_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8_close, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jButton_Register.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton_Register.setText("Register");
        jButton_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_RegisterMouseExited(evt);
            }
        });
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setText("                   Full Name  :");

        jTextField_Fullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Fullname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_FullnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_FullnameFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel3.setText("                 UserName  :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel4.setText("                 Password  :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel5.setText("     ConfirmPassword  :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel6.setText("                  Phone  :");

        jTextField_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusLost(evt);
            }
        });

        jTextField_Phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_PhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_PhoneFocusLost(evt);
            }
        });
        jTextField_Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhoneKeyTyped(evt);
            }
        });

        jPasswordField_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_1FocusLost(evt);
            }
        });

        jPasswordField_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_2FocusLost(evt);
            }
        });

        jLabel_Login_Account.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Login_Account.setForeground(new java.awt.Color(0, 255, 51));
        jLabel_Login_Account.setText("       >> Already Have an Account ? Login     ");
        jLabel_Login_Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Login_AccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Login_AccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Login_AccountMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Contact :  Ajeetjha50@gmail.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Login_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Fullname, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                            .addComponent(jTextField_Username)
                            .addComponent(jPasswordField_1)
                            .addComponent(jPasswordField_2)
                            .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jPasswordField_1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Login_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RegisterMouseEntered
      
        jButton_Register.setBackground(new Color(0,101,183)); 
        
    }//GEN-LAST:event_jButton_RegisterMouseEntered

    private void jButton_RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RegisterMouseExited
      
          // set jButton background
          
        jButton_Register.setBackground(new Color(0,84,104));
        
    }//GEN-LAST:event_jButton_RegisterMouseExited

    private void jTextField_PhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhoneKeyTyped
        
        // allow only numbers
        
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
        
    }//GEN-LAST:event_jTextField_PhoneKeyTyped

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed

        String fname = jTextField_Fullname.getText();
        String username = jTextField_Username.getText();
        String pass1 = String.valueOf(jPasswordField_1.getPassword());
        String pass2 = String.valueOf(jPasswordField_2.getPassword());
        String phone =jTextField_Phone.getText();
        
        if(verifyFields())
        {
            if(!checkUsername(username))
            {
                PreparedStatement ps;
                ResultSet rs;
                String registerUserQuery = "INSERT INTO `user`(`full_name`, `username`, `password`, `phone`) VALUES (?,?,?,?)";
                
                try{
                    ps = My_CNX.getConnection().prepareStatement(registerUserQuery);
                   
                      ps.setString(1, fname);
                      ps.setString(2, username);
                      ps.setString(3, pass1);
                      ps.setString(4, phone);
                      
                      
                      if(ps.executeUpdate() != 0){
                          JOptionPane.showMessageDialog(null, "Your Account Has Been Created");
                      }else{
                          JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                      }
                      
                } catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
                   
              
            }
        }
        
        
    }//GEN-LAST:event_jButton_RegisterActionPerformed

    private void jLabel_Login_AccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Login_AccountMouseEntered
        
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0,204,0));
        jLabel_Login_Account.setBorder(label_border);
        
    }//GEN-LAST:event_jLabel_Login_AccountMouseEntered

    private void jLabel_Login_AccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Login_AccountMouseExited
        
        Border label_create_accont_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jLabel_Login_Account.setBorder(label_create_accont_border);
        
    }//GEN-LAST:event_jLabel_Login_AccountMouseExited

    private void jLabel_Login_AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Login_AccountMouseClicked
        
        Login lf = new Login();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jLabel_Login_AccountMouseClicked

    private void jLabel7_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7_minimizeMouseEntered
        
          Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel7_minimize.setBorder(label_border);
        jLabel7_minimize.setForeground(Color.white);
        
    }//GEN-LAST:event_jLabel7_minimizeMouseEntered

    private void jLabel7_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7_minimizeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel7_minimize.setBorder(label_border);
        jLabel7_minimize.setForeground(Color.black);
    }//GEN-LAST:event_jLabel7_minimizeMouseExited

    private void jLabel8_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8_closeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel8_close.setBorder(label_border);
        jLabel8_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel8_closeMouseEntered

    private void jLabel8_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8_closeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel8_close.setBorder(label_border);
        jLabel8_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel8_closeMouseExited

    private void jLabel7_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7_minimizeMouseClicked
       
        this.setState(JFrame.ICONIFIED);
        
    }//GEN-LAST:event_jLabel7_minimizeMouseClicked

    private void jLabel8_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8_closeMouseClicked
        
         System.exit(0);
        
    }//GEN-LAST:event_jLabel8_closeMouseClicked

    private void jTextField_FullnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_FullnameFocusGained
         
         // clear the textfield on focus if the text is "Fullname"
        if(jTextField_Fullname.getText().trim().toLowerCase().equals("enter the full name"))
        {
            jTextField_Fullname.setText("");
            jTextField_Fullname.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_jTextField_FullnameFocusGained

    private void jTextField_FullnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_FullnameFocusLost
        
         //if text field is equal to user name and ampty
        //we will set the "Fullname " text in the field 
        // on focus lost event 
        
         if(jTextField_Fullname.getText().trim().equals("") || 
           jTextField_Fullname.getText().trim().toLowerCase().equals("enter the full name"))
        {
            jTextField_Fullname.setText("enter the full name");
            jTextField_Fullname.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_jTextField_FullnameFocusLost

    private void jTextField_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusGained
     
      // clear the textfield on focus if the text is "Fullname"
        if(jTextField_Username.getText().trim().toLowerCase().equals("enter the user name"))
        {
            jTextField_Username.setText("");
            jTextField_Username.setForeground(Color.black);
        }  
        
    }//GEN-LAST:event_jTextField_UsernameFocusGained

    private void jTextField_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusLost
      
       //if text field is equal to user name and ampty
        //we will set the "Fullname " text in the field 
        // on focus lost event 
        
         if(jTextField_Username.getText().trim().equals("") || 
            jTextField_Username.getText().trim().toLowerCase().equals("enter the user name"))
        {
             jTextField_Username.setText("enter the user name");
             jTextField_Username.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_jTextField_UsernameFocusLost

    private void jPasswordField_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_1FocusGained
        
         // clear the password field on focus if the text is "password"
        // get the password text
        
        String pass = String.valueOf(jPasswordField_1.getPassword());
        
        if(pass.trim().toLowerCase().equals("password"))
        {
            jPasswordField_1.setText("");
            jPasswordField_1.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_1FocusGained

    private void jPasswordField_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_1FocusLost
        
         // if the password field is equal to password or empty
        // we will set the "password" text in the field 
        // on focus lost event
        // get the password text
        
        String pass = String.valueOf(jPasswordField_1.getPassword());
        
        if(pass.trim().equals("") || 
           pass.trim().toLowerCase().equals("password"))
        {
            jPasswordField_1.setText("password");
            jPasswordField_1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordField_1FocusLost

    private void jPasswordField_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_2FocusGained
        
        // clear the password field on focus if the text is "password"
        // get the password text
        
        String pass = String.valueOf(jPasswordField_2.getPassword());
        
        if(pass.trim().toLowerCase().equals("password"))
        {
            jPasswordField_2.setText("");
            jPasswordField_2.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_jPasswordField_2FocusGained

    private void jPasswordField_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_2FocusLost
        
         // if the password field is equal to password or empty
        // we will set the "password" text in the field 
        // on focus lost event
        // get the password text
        
        String pass = String.valueOf(jPasswordField_2.getPassword());
        
        if(pass.trim().equals("") || 
           pass.trim().toLowerCase().equals("password"))
        {
            jPasswordField_2.setText("password");
            jPasswordField_2.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_jPasswordField_2FocusLost

    private void jTextField_PhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_PhoneFocusGained
        
        // clear the textfield on focus if the text is "Phone"
        if(jTextField_Phone.getText().trim().toLowerCase().equals("enter the phone number"))
        {
            jTextField_Phone.setText("");
            jTextField_Phone.setForeground(Color.black);
        }  
        
    }//GEN-LAST:event_jTextField_PhoneFocusGained

    private void jTextField_PhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_PhoneFocusLost
        //if text field is equal to user name and ampty
        //we will set the "Phone " text in the field 
        // on focus lost event 
        
         if(jTextField_Phone.getText().trim().equals("") || 
            jTextField_Phone.getText().trim().toLowerCase().equals("enter the phone number"))
        {
             jTextField_Phone.setText("enter the phone number");
             jTextField_Phone.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_PhoneFocusLost
      
          //create a unction to verify the empty fields
    
    public boolean verifyFields()
    {
        String fname = jTextField_Fullname.getText();
        String uname = jTextField_Username.getText();
        String phone = jTextField_Phone.getText();
        String pass1 = String.valueOf(jPasswordField_1.getPassword());
        String pass2 = String.valueOf(jPasswordField_2.getPassword());
        
        // check empty fields
        
        if(fname.trim().equals("") || uname.trim().equals("")  || phone.trim().equals("") || pass1.trim().equals("")
                || pass2.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or more Fields Are Empty","Empty Fields",2);
            return false;
        }
        
        // check if the two password are equals
        
        else if(!pass1.equals(pass2))
        {
            JOptionPane.showMessageDialog(null, "Password doesn't Match","Confirm Password",2);
            return false;
        }
        
        // if everything is ok
        
        else{
            return true;
        }
        
    }
    
    
         //create a unction to check if the entered username already exist in the database
    
    public boolean checkUsername(String username)
    {
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query ="SELECT * FROM `user` WHERE `username`= ?";
        
        try {
            
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            
            if(rs.next())
            {
                username_exist = true;
                JOptionPane.showMessageDialog(null,"This Username is Already Taken, Choose Another One","Username Failed",2);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        return username_exist;
        
    }
    
            
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7_minimize;
    private javax.swing.JLabel jLabel8_close;
    private javax.swing.JLabel jLabel_Login_Account;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_1;
    private javax.swing.JPasswordField jPasswordField_2;
    private javax.swing.JTextField jTextField_Fullname;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
